version: '3.8'

services:

  mongoDb:
    image: mongo:6.0
    volumes:
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:?}
    ports:
      - ${DATABASE_PORT:-27017}:27017
    restart: always
      

  backendDisruptive:
    image: disruptive-delivery-backend
    build:
      context: ./backend
    depends_on:
      - mongoDb
    environment:
      DATABASE_HOST: mongoDb
      DATABASE_PASSWORD: ${DATABASE_ROOT_PASSWORD:?}
      DATABASE_PORT: 27017
      PORT_TO_SHOW: ${BACKEND_PORT:?}
    ports:
      - ${BACKEND_PORT:?}:80

  frontendDisruptive:
    image: disruptive-delievry-frontend
    build:
      context: ./frontend
    environment:
      - BACKEND
    ports:
      - ${FRONTEND_PORT:?}:80